spring.application.name=backend

server.port=8080

# BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://dpg-d836t2rtqb8s73dd2hpg-a.virginia-postgres.render.com:5432/a3_validacao_token
spring.datasource.username=marcus
spring.datasource.password=wdLLToUuICxuwV2xC9T0yiTuBWjAcadL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=naorespondabuynow@gmail.com
spring.mail.password=mculecjktrmgxvli
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com