spring.application.name=backend

# Porta dinamica obrigatoria para a Railway
server.port=${PORT:8080}
server.address=0.0.0.0

# Conexao com o Banco de Dados PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d836t2rtqb8s73dd2hpg-a.virginia-postgres.render.com:5432/a3_validacao_token
spring.datasource.username=marcus
spring.datasource.password=wdLLToUuICxuwV2xC9T0yiTuBWjAcadL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config - Totalmente limpo e sem caracteres ocultos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa o starter de email nativo para nao dar conflito com a API HTTP da Resend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration