spring.application.name=backend

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d836t2rtqb8s73dd2hpg-a.virginia-postgres.render.com:5432/a3_validacao_token}
spring.datasource.username=${DB_USER:marcus}
spring.datasource.password=${DB_PASSWORD:wdLLToUuICxuwV2xC9T0yiTuBWjAcadL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURAÇÃO DO DISPARADOR DE EMAIL (naorespondabuynow@gmail.com)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=naorespondabuynow@gmail.com

# IMPORTANTE: Esta senha de app (mculecjktrmgxvli) PRECISA ter sido gerada
# dentro do painel de segurança da conta naorespondabuynow@gmail.com
spring.mail.password=mculecjktrmgxvli

# Canal SSL Direto (Porta 465) para furar o bloqueio de containers do Render
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true

# Desativa o STARTTLS da porta antiga para não dar conflito de protocolo
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

# Protocolos de Criptografia aceitos pelo Google
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Timeouts de rede em milissegundos
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000